name: xelatex resume generator
on:
  push:
    branches: [main]
jobs:
    latex_pdf:
      runs-on: ubuntu-latest
      steps:
        - name: checkout repo
          uses: actions/checkout@v2.3.4
        - uses: xu-cheng/latex-action@v2
          with:
            root_file: resume.tex
            latexmk_use_xelatex: true
            continue_on_error: true
            args: "-f"
            
        - name: Upload PDF file
          uses: actions/upload-artifact@v3
          with:
            name: PDF
            path: resume.pdf
        - name: Post Processing
          run: |
            mkdir resumeBuild
            cp resume.pdf resumeBuild/
            cp index.html resumeBuild/
        # - name: Git add
        #   run: git add resumeBuild/
        - run: npm ci
        - uses: FirebaseExtended/action-hosting-deploy@v0
          with:
            repoToken: '${{ secrets.GITHUB_TOKEN }}'
            firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JAYESH_POTLABATTINI }}'
            projectId: jayesh-potlabattini
            channelId: live
