name: xelatex resume generator
on:
  push:
    branches: [main]
jobs:
    latex_pdf:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: sudo apt-get install texlive-xetex
        - run: xelatex resume.tex
        - name: Upload PDF file
          uses: actions/upload-artifact@v3
          with:
            name: PDF
            path: resume.pdf
        - name: Post Processing
          run: |
            mkdir resumeBuild
            cp resume.pdf resumeBuild/
            cp index.html resumeBuild/
        - name: Git add
          run: git add resumeBuild/
        - uses: FirebaseExtended/action-hosting-deploy@v0
          with:
            repoToken: '${{ secrets.GITHUB_TOKEN }}'
            firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JAYESH_POTLABATTINI }}'
            projectId: resume-jayesh-potlabattini
